### ISSUE TITLE
Current room not greyed out after load 

### ISSUE THREAD

**Issue by 01010100010100100100100101000111** [DRincs-Productions/NQTR-toolkit#42]
Go to any room, save the game 

Close the game and restart it, 

Load the save, the current room navigation icon will not be greyed out.

**Comment by BlackRam-oss** [comment]
I'm not sure what might be causing the error, but I think it can only be in two places:  


Here I add the rooms buttons is in case it is the current room: I set it as selected:
https://github.com/DRincs-Productions/NQTR-toolkit/blob/main/game/tool/nqtr_screens.rpy#L155
cur_room can be nothing.
The line:
selected room == cur_room
It should be improved in: (maybe it also solves the problem)  
selected true if cur_room and cur_room.id == room.id else false

Or for some reason cur_room becomes null after loading, caused by one of these functions:
https://github.com/DRincs-Productions/NQTR-toolkit/blob/main/game/tool/core.rpy#L2
